### ISSUE TITLE
I receive an error on make command

### ISSUE THREAD

**Issue by dspstudio** [wilvk/pbe-linux#2]
[root@dev pbec]# make
g++ -c -Wall -g -std=c++11 source/common/retrievestruct.cpp -o source/common/retrievestruct.o -I./includes -I./includes/external
source/common/retrievestruct.cpp: In member function 'std::vector<ATOM_MCLK_ENTRY> RetrieveStruct::AtomMemClockEntries(Buffer*, int, int)':
source/common/retrievestruct.cpp:74:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < atom_mclk_entries.size(); i++)
                                              ^
source/common/retrievestruct.cpp: In member function 'std::vector<ATOM_SCLK_ENTRY> RetrieveStruct::AtomSysClockEntries(Buffer*, int, int)':
source/common/retrievestruct.cpp:99:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < atom_sclk_entries.size(); i++)
                                              ^
g++ -c -Wall -g -std=c++11 source/common/savestruct.cpp -o source/common/savestruct.o -I./includes -I./includes/external
source/common/savestruct.cpp: In instantiation of 'static std::vector<unsigned char> SaveStruct::toBytes(T&) [with T = ATOM_VRAM_TIMING_ENTRY]':
source/common/savestruct.cpp:19:70:   required from here
source/common/savestruct.cpp:9:42: error: 'memcpy' was not declared in this scope
   memcpy(byteArray, &memStruct, arraySize);
                                          ^
make: *** [source/common/savestruct.o] Error 1

**Comment by wilvk** [comment]
What OS are you trying to run this on?

**Comment by dspstudio** [comment]
Linux dev 2.6.32-042stab116.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wilvk** [comment]
I haven't tested it with RHEL - YMMV - would suggest doing a PR if this is something you need.
I can tell you it definitely works on Ubuntu 16.04

**Comment by dspstudio** [comment]
Ok thank you , ill try on Ubuntu.
