### ISSUE TITLE
Cant Compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by nvieirapt** [wilvk/pbe-linux#4]
$ make
g++ -c -Wall -g -std=c++11 source/common/retrievestruct.cpp -o source/common/retrievestruct.o -I./includes -I./includes/external
source/common/retrievestruct.cpp: In member function ‘std::vector<ATOM_MCLK_ENTRY> RetrieveStruct::AtomMemClockEntries(Buffer*, int, int)’:
source/common/retrievestruct.cpp:74:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < atom_mclk_entries.size(); i++)
                     ^
source/common/retrievestruct.cpp: In member function ‘std::vector<ATOM_SCLK_ENTRY> RetrieveStruct::AtomSysClockEntries(Buffer*, int, int)’:
source/common/retrievestruct.cpp:99:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < atom_sclk_entries.size(); i++)
                     ^
g++ -c -Wall -g -std=c++11 source/common/savestruct.cpp -o source/common/savestruct.o -I./includes -I./includes/external
source/common/savestruct.cpp: In instantiation of ‘static std::vector<unsigned char> SaveStruct::toBytes(T&) [with T = ATOM_VRAM_TIMING_ENTRY]’:
source/common/savestruct.cpp:19:70:   required from here
source/common/savestruct.cpp:9:9: error: ‘memcpy’ was not declared in this scope
   memcpy(byteArray, &memStruct, arraySize);
         ^
Makefile:52: recipe for target 'source/common/savestruct.o' failed
make: *** [source/common/savestruct.o] Error 1

**Comment by wilvk** [comment]
This should be working now. I've also added a Docker container for Ubuntu for doing the build if your libraries don't install for some reason:

`make dockerbuild-ubuntu1604`

Cheers,
