### ISSUE TITLE
cant compile on 16.04.3

### ISSUE THREAD

**Issue by volandku** [wilvk/pbe-linux#1]
make
g++ -c -Wall -g -std=c++11 console.cpp -o console.o
console.cpp: In static member function ‘static void Console::PrintDeviceValidation(std::vector<short unsigned int>, WORD)’:
console.cpp:225:97: error: no matching function for call to ‘find(std::vector<short unsigned int>::iterator, std::vector<short unsigned int>::iterator, WORD&)’
 d::begin(SupportedDeviceIDs), std::end(SupportedDeviceIDs), DeviceId) != std::e
                                                                     ^
In file included from /usr/include/c++/5/bits/locale_facets.h:48:0,
                 from /usr/include/c++/5/bits/basic_ios.h:37,
                 from /usr/include/c++/5/ios:44,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from console.h:3,
                 from console.cpp:1:
/usr/include/c++/5/bits/streambuf_iterator.h:369:5: note: candidate: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^
/usr/include/c++/5/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
console.cpp:225:97: note:   ‘__gnu_cxx::__normal_iterator<short unsigned int*, std::vector<short unsigned int> >’ is not derived from ‘std::istreambuf_iterator<_CharT>’
 d::begin(SupportedDeviceIDs), std::end(SupportedDeviceIDs), DeviceId) != std::e
                                                                     ^
console.cpp: In static member function ‘static void Console::PrintDefaultAtomVramTimingEntriesInfo(std::vector<ATOM_VRAM_TIMING_ENTRY>)’:
console.cpp:304:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < AtomVramTimingEntries.size(); i++)
                     ^
Makefile:37: ошибка выполнения рецепта для цели «console.o»
make: *** [console.o] Ошибка 1

**Comment by wilvk** [comment]
Thanks for this. It should be working on Ubuntu now.

**Comment by twistedmonkey** [comment]
i cant compile on ubuntu 16.04

$ make
g++ -c -Wall -g -std=c++11 source/common/savestruct.cpp -o source/common/savestruct.o -I./includes -I./includes/external
source/common/savestruct.cpp: In instantiation of ‘static std::vector<unsigned char> SaveStruct::toBytes(T&) [with T = ATOM_VRAM_TIMING_ENTRY]’:
source/common/savestruct.cpp:19:70:   required from here
source/common/savestruct.cpp:9:9: error: ‘memcpy’ was not declared in this scope
   memcpy(byteArray, &memStruct, arraySize);
         ^
Makefile:52: recipe for target 'source/common/savestruct.o' failed
make: *** [source/common/savestruct.o] Error 1
nuno@HP-Z800-Workstation:~/pbec$ make clean
find . -name '*.o' -type f -delete; \
	rm pbec tests
rm: cannot remove 'pbec': No such file or directory
rm: cannot remove 'tests': No such file or directory
Makefile:40: recipe for target 'clean' failed
make: *** [clean] Error 1
nuno@HP-Z800-Workstation:~/pbec$ make
g++ -c -Wall -g -std=c++11 source/common/retrievestruct.cpp -o source/common/retrievestruct.o -I./includes -I./includes/external
source/common/retrievestruct.cpp: In member function ‘std::vector<ATOM_MCLK_ENTRY> RetrieveStruct::AtomMemClockEntries(Buffer*, int, int)’:
source/common/retrievestruct.cpp:74:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < atom_mclk_entries.size(); i++)
                     ^
source/common/retrievestruct.cpp: In member function ‘std::vector<ATOM_SCLK_ENTRY> RetrieveStruct::AtomSysClockEntries(Buffer*, int, int)’:
source/common/retrievestruct.cpp:99:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < atom_sclk_entries.size(); i++)
                     ^
g++ -c -Wall -g -std=c++11 source/common/savestruct.cpp -o source/common/savestruct.o -I./includes -I./includes/external
source/common/savestruct.cpp: In instantiation of ‘static std::vector<unsigned char> SaveStruct::toBytes(T&) [with T = ATOM_VRAM_TIMING_ENTRY]’:
source/common/savestruct.cpp:19:70:   required from here
source/common/savestruct.cpp:9:9: error: ‘memcpy’ was not declared in this scope
   memcpy(byteArray, &memStruct, arraySize);
         ^
Makefile:52: recipe for target 'source/common/savestruct.o' failed
make: *** [source/common/savestruct.o] Error 1
